name: ilp_file_codec
description: .ilp file codec.
version: 1.0.14
homepage: https://github.com/whimsy-ai/ilp_file_codec


environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  archive: ^3.3.7
  collection: ^1.17.0
  crypto: ^3.0.3
  path: ^1.8.3
  protobuf: ^3.0.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
